[build]
  publish = 'dist/'
  command = 'yarn build'
  [build.environment]
    NETLIFY_USE_YARN = 'true'
    YARN_FLAGS = '--immutable'
    CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
    TERM = "xterm"
[[plugins]]
  package = "netlify-plugin-a11y"
  [plugins.inputs]
    checkPaths = ['/']
[[plugins]]
  package = "netlify-plugin-cypress"
  [plugins.inputs]
    record = true
[[redirects]]
  from = '/api/*'
  to = '/.netlify/functions/:splat'
  status = 200