[build]
  publish = 'packages/ui/dist/'
  command = 'yarn astro:build'
  [build.environment]
    NETLIFY_USE_YARN = 'true'
    CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
    TERM = "xterm"
[functions]
  directory = 'packages/functions'
[[plugins]]
  package = "netlify-plugin-cypress"
  [plugins.inputs]
    record = true
[[redirects]]
  from = '/api/*'
  to = '/.netlify/functions/:splat'
  status = 200