# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Linting and Testing

on:
  pull_request:
    branches: [main]

jobs:
  install:
    name: install
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - name: Validate cache
        env:
          YARN_NODE_LINKER: node_modules
          YARN_ENABLE_SCRIPTS: false
        run: yarn --immutable

  linting:
    needs: [install]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Linting
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install --immutable
      - run: yarn lint

  testing:
    needs: [install]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Linting
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install --immutable
      - run: yarn test
